---
- name: Manage Essential Services
  hosts: all
  become: yes
  tasks:
    - name: Start the service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
      when: service_action == 'start'

    - name: Stop the service
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: stopped
      when: service_action == 'remove'

    - name: Remove the service package
      ansible.builtin.yum:
        name: "{{ service_name }}"
        state: absent
      when: service_action == 'remove'
