---
- name: Manage Service
  hosts: all
  become: yes
  vars_prompt:
    - name: service_action
      prompt: "Select the action to perform (start/remove)"
      private: no

    - name: service_name
      prompt: "Enter the service name"
      private: no

  tasks:
    - name: Ensure the service is started
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: started
      when: service_action == 'start'

    - name: Ensure the service is removed
      ansible.builtin.systemd:
        name: "{{ service_name }}"
        state: stopped
      when: service_action == 'remove'

    - name: Remove the service package
      ansible.builtin.yum:
        name: "{{ service_name }}"
        state: absent
      when: service_action == 'remove'
